export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const SIGN_UP = 'SIGN_UP';
export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const AUTHENTICATE_TOKEN = 'AUTHENTICATE_TOKEN';

export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_BY_CATEGORY = 'FETCH_PRODUCTS_BY_CATEGORY';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const CHECK_PRODUCT_QUANTITY = 'CHECK_PRODUCT_QUANTITY';
export const ADD_NEW_PRODUCT_IMAGE = 'ADD_NEW_PRODUCT_IMAGE';
export const SET_MAIN_PRODUCT_IMAGE = 'SET_MAIN_PRODUCT_IMAGE';
export const ADD_ALL_PRODUCT_IMAGES = 'ADD_ALL_PRODUCT_IMAGES';
export const DELETE_PRODUCT_IMAGE = 'DELETE_PRODUCT_IMAGE';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';

export const FETCH_ATTRIBUTES = 'FETCH_ATTRIBUTES';
export const FETCH_ATTRIBUTE = 'FETCH_ATTRIBUTE';
export const FETCH_ATTRIBUTES_BY_CATEGORY = 'FETCH_ATTRIBUTES_BY_CATEGORY';
export const UPDATE_ATTRIBUTE = 'UPDATE_ATTRIBUTE';
export const ADD_ATTRIBUTE = 'ADD_ATTRIBUTE';
export const ADD_ATTRIBUTES = 'ADD_ATTRIBUTES';
export const DELETE_ATTRIBUTE= 'DELETE_ATTRIBUTE';

export const CURRENT_USER = 'CURRENT_USER';

export const FETCH_USER = 'FETCH_USER';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CREATE_POSTMAN = 'CREATE POSTMAN';

export const FETCH_SHOPPING_CART = 'FETCH_SHOPPING_CART';
export const ADD_TO_SHOPPING_CART = 'ADD_TO_SHOPPING_CART';
export const DELETE_FROM_SHOPPING_CART = 'DELETE_FROM_SHOPPING_CART';
export const UPDATE_PRODUCT_IN_CART = 'UPDATE_PRODUCT_IN_CART';

export const MAKE_ORDER = 'MAKE_ORDER';
export const FETCH_ORDERS = 'FETCH_ORDERS';
export const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';
export const FETCH_ORDERS_BY_POSTMAN = 'FETCH_ORDERS_BY_POSTMAN';
export const FETCH_ORDERS_BY_ADMIN = 'FETCH_ORDERS_BY_ADMIN';